### ISSUE TITLE
Grating speeds and updated pxs/deg

### ISSUE THREAD

**Issue by babinod** [tbenst/glia#11]
Checkerboard contrast is definitely using the updated measurements of px/deg, but it seems that data processing/classification for grating speeds may not be using the updated numbers for calculating logMAR. Could you please confirm. For example see 171117, E1 and E2 are checkerboard and E3 and E4 are gratings.

**Comment by tbenst** [comment]
Glia uses 12.524 px/deg for all programs. However, an older version of EyeCandy did still have 7.5 px/deg for some stimuli--fixed in #9. Note that in this case, Glia would output the correct logMAR even though the EyeCandy protocol would be off, so the charts should always be correct. Let me know if you saw anything that makes you think differently--couldn't connect to Sauron just now

**Comment by tbenst** [comment]
Just checked R1_E4. Looks like eyecandy protocol is startLogMar=2.1, and the chart matches this--closing for now but feel free to reopen
